language: php
php:
  - '7.0'
dist: xenial

sudo: required

services:
  - docker

script: composer run test 

before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then 
    docker build -t studionone/travis-flynn-test:latest .;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker build -t studionone/travis-flynn-test:develop .;
    fi
  - docker ps -a

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_PRODUCTION_EMAIL" -u="$DOCKER_PRODUCTION_USERNAME" -p="$DOCKER_PRODUCTION_PASSWORD" repository.studionone.io;
    docker push studionone/travis-flynn-test;
    fi
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker login -e="$DOCKER_PRODUCTION_EMAIL" -u="$DOCKER_PRODUCTION_USERNAME" -p="$DOCKER_PRODUCTION_PASSWORD" repository.studionone.io;
    docker push studionone/travis-flynn-test;
    fi 
