language: php
php:
  - '7.0'
dist: xenial

sudo: required

services:
  - docker

deploy:
  provider: s3
  access_key_id: $S3_ACCESS_KEY
  secret_access_key: $S3_SECRET_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true

script: composer test 

before_install:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -t studionone/travis-flynn-test:$TAG .
  - docker ps -a
  - docker run studionone/travis-flynn-test:$TAG /bin/sh -c "composer test"

after_success:
  - export REGISTRY=repository.studionone.io
  - export REPO=studionone/travis-flynn-test
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker login -u $DOCKER_PRODUCTION_USERNAME -p $DOCKER_PRODUCTION_PASSWORD $REGISTRY
  - docker tag $REGISTRY/$REPO:$COMMIT $REPO:$TAG
  - docker tag $REGISTRY/$REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REGISTRY/$REPO
