language: bash
sudo: required
services:
  - docker

before_install:
  - export REGISTRY=registry.studionone.io
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export DOCKER_ENV=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "production"; else echo "development" ; fi`
  - docker build --build-arg env=$DOCKER_ENV -t $TRAVIS_REPO_SLUG:$TAG .

install: true

# This is the section that you may need to configure your tests
script: 
  - docker run -i --rm --entrypoint=/bin/sh $TRAVIS_REPO_SLUG:$TAG -c "cd /var/www && composer self-update && composer test"

after_success:
  - docker login -u $DOCKER_PRODUCTION_USERNAME -p $DOCKER_PRODUCTION_PASSWORD $REGISTRY
  - docker tag $TRAVIS_REPO_SLUG:$TAG $REGISTRY/$TRAVIS_REPO_SLUG:$TAG
  - docker push $REGISTRY/$TRAVIS_REPO_SLUG:$TAG
