language: php
sudo: required
services:
  - docker

before_install:
  - export REGISTRY=repository.studionone.io
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export DOCKER_ENV=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "production"; else echo "development" ; fi`
  - docker build --build-arg env=$DOCKER_ENV -t $TRAVIS_REPO_SLUG:$TAG .

script: docker run -i --rm $TRAVIS_REPO_SLUG:$TAG "cd /var/www ; composer test"

after_success:
  - docker login -u $DOCKER_PRODUCTION_USERNAME -p $DOCKER_PRODUCTION_PASSWORD $REGISTRY
  - docker tag $TRAVIS_REPO_SLUG:$TAG $REGISTRY/$TRAVIS_REPO_SLUG:$TAG
  - docker push $REGISTRY/$TRAVIS_REPO_SLUG:$TAG
